import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { activityApi } from "../api/governance";

function formatDate(value) { return value ? new Date(value).toLocaleString() : "—"; }

export default function AccountActivityPage() {
  const [cursor, setCursor] = useState("");
  const [state, setState] = useState({ status: "loading", events: [], nextCursor: "", error: "" });
  useEffect(() => { let active = true; activityApi.list(cursor).then((result) => { if (active) setState({ status: "ready", events: result.events || result.items || [], nextCursor: result.nextCursor || "", error: "" }); }).catch((error) => { if (active) setState({ status: "error", events: [], nextCursor: "", error: error.message }); }); return () => { active = false; }; }, [cursor]);
  return <main className="px-5 py-8 sm:px-8 lg:px-10 lg:py-10"><Link className="text-sm font-bold text-slate-500 hover:text-emerald-700" to="/dashboard/profile">← Profile</Link><div className="mt-5"><p className="text-sm font-bold text-emerald-700">Account security</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Account activity</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Review customer-visible account, request, quote, payment, and delivery actions. Private staff notes are never shown here.</p></div>{state.status === "loading" && <div className="mt-8 h-64 animate-pulse rounded-[2rem] bg-white" />}{state.status === "error" && <div className="mt-8 rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800" role="alert">{state.error}</div>}{state.status === "ready" && <section className="mt-8 rounded-[2rem] border border-slate-200 bg-white p-6 sm:p-8">{state.events.length ? <ol className="space-y-6">{state.events.map((event, index) => <li key={event.id || index} className="border-l-2 border-emerald-200 pl-5"><p className="text-xs text-slate-500">{formatDate(event.createdAt || event.timestamp)}</p><h2 className="mt-1 font-bold">{event.customerLabel || event.label}</h2><p className="mt-1 text-sm text-slate-600">{event.actorLabel || "Hakim Plus"}{event.entityLabel ? ` · ${event.entityLabel}` : ""}</p>{event.note && <p className="mt-2 text-sm leading-6 text-slate-600">{event.note}</p>}</li>)}</ol> : <div className="py-8 text-center"><h2 className="font-bold">No account activity yet</h2><p className="mt-2 text-sm text-slate-600">Security and service events will appear when available.</p></div>}{state.nextCursor && <div className="mt-8 border-t border-slate-100 pt-5 text-center"><button className="rounded-xl border border-slate-300 px-5 py-2 text-sm font-bold" type="button" onClick={() => setCursor(state.nextCursor)}>Load older activity</button></div>}</section>}</main>;
}
