import { useEffect, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { adminOrdersApi } from "../api/orders";
import { uploadProtectedDeliveryProof, validateRequestFile } from "../api/protectedUploads";
import { formatMinorAmount } from "../quotes/quoteSchema";

const pagePadding = "px-5 py-8 sm:px-8 lg:px-10 lg:py-10";
const operationalQueues = [["active","Paid / active"],["out_for_delivery","Out for delivery"],["delivery_failed","Delivery failed"]];
const operationalQueueValues = new Set(operationalQueues.map(([value]) => value));

function formatDate(value) {
  if (!value) return "Not available";
  return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
}
function Loading() { return <div className="mt-8 h-48 animate-pulse rounded-[2rem] bg-white" role="status" />; }
function ErrorMessage({ message }) { return <div className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800" role="alert">{message}</div>; }

export function AdminOrdersPage({ completedOnly = false }) {
  const [searchParams, setSearchParams] = useSearchParams();
  const requestedQueue = searchParams.get("queue") || "active";
  const initialQueue = completedOnly ? "completed" : operationalQueueValues.has(requestedQueue) ? requestedQueue : "active";
  const [queue, setQueue] = useState(initialQueue);
  const [search, setSearch] = useState("");
  const [state, setState] = useState({ status: "loading", orders: [], error: "" });

  async function load(selectedQueue = queue, selectedSearch = search) {
    setState((current) => ({ ...current, status: "loading" }));
    try { const result = await adminOrdersApi.list({ queue: selectedQueue, search: selectedSearch }); setState({ status: "ready", orders: result.orders || result.items || [], error: "" }); }
    catch (error) { setState({ status: "error", orders: [], error: error.message }); }
  }
  useEffect(() => { let active = true; adminOrdersApi.list({ queue: initialQueue }).then((result) => { if (active) setState({ status: "ready", orders: result.orders || result.items || [], error: "" }); }).catch((error) => { if (active) setState({ status: "error", orders: [], error: error.message }); }); return () => { active = false; }; }, [initialQueue]);
  function chooseQueue(value) { setQueue(value); setSearchParams({ queue: value }); load(value, search); }

  const title = completedOnly ? "Completed orders" : "Orders and delivery";
  const description = completedOnly ? "A read-only history of successfully delivered orders." : "Prepare verified paid orders, assign delivery, dispatch, and record delivery outcomes.";
  const emptyLabel = completedOnly ? "No completed orders" : "No orders in this queue";
  const detailBasePath = completedOnly ? "/admin/completed-orders" : "/admin/orders";

  return <main className={pagePadding}><div><p className="text-sm font-bold text-emerald-700">Fulfillment operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h1><p className="mt-3 text-sm text-slate-600">{description}</p></div><section className="mt-8 rounded-[2rem] border border-slate-200 bg-white p-4">{!completedOnly && <div className="flex flex-wrap gap-2">{operationalQueues.map(([value,label]) => <button key={value} className={`rounded-full px-4 py-2 text-sm font-bold ${queue === value ? "bg-slate-950 text-white" : value === "delivery_failed" ? "bg-red-50 text-red-700" : "bg-slate-100 text-slate-600"}`} type="button" onClick={() => chooseQueue(value)}>{label}</button>)}</div>}<form className={completedOnly ? "flex gap-2" : "mt-4 flex gap-2"} onSubmit={(event) => { event.preventDefault(); load(); }}><label className="sr-only" htmlFor="order-search">Search orders</label><input id="order-search" className="min-w-0 flex-1 rounded-xl border border-slate-300 px-4 py-3 text-sm" placeholder="Order number, beneficiary, customer" value={search} onChange={(event) => setSearch(event.target.value)} /><button className="rounded-xl bg-emerald-600 px-5 text-sm font-bold text-white" type="submit">Search</button></form></section>{state.status === "loading" && <Loading />}{state.status === "error" && <ErrorMessage message={state.error} />}{state.status === "ready" && <section className="mt-6 space-y-3">{state.orders.length === 0 ? <div className="rounded-[2rem] border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-bold">{emptyLabel}</h2></div> : state.orders.map((order) => { const id = order.publicId || order.id; return <Link key={id} className={`block rounded-2xl border bg-white p-5 transition hover:border-emerald-400 hover:shadow-md ${order.overdue ? "border-red-300" : "border-slate-200"}`} to={`${detailBasePath}/${encodeURIComponent(id)}`}><div className="grid gap-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-400">{order.orderNumber || id}</p>{order.overdue && <span className="rounded-full bg-red-700 px-2 py-1 text-[10px] font-bold text-white">OVERDUE</span>}</div><h2 className="mt-2 font-bold">{order.beneficiary?.fullName || order.beneficiaryName}</h2><p className="mt-1 text-sm text-slate-500">{order.itemCount || order.items?.length || 0} item(s) · {formatMinorAmount(order.amountMinor, order.currency)}</p></div><div className="sm:text-right"><span className="inline-flex rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">{order.statusLabel || String(order.status).replaceAll("_", " ")}</span><p className="mt-2 text-xs text-slate-500">Delivery: {order.deliveryStatusLabel || "Not dispatched"}</p></div></div></Link>; })}</section>}
  </main>;
}

function Info({ label, value }) { return <div><dt className="text-xs font-bold uppercase tracking-[0.12em] text-slate-400">{label}</dt><dd className="mt-2 whitespace-pre-wrap text-sm font-semibold text-slate-800">{value || "Not provided"}</dd></div>; }

function DeliveryPersonSummary({ assignment, onEdit }) {
  return <section className="rounded-[2rem] border border-blue-200 bg-blue-50 p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-700">Delivery assignment</p><h2 className="mt-2 text-lg font-bold text-blue-950">Delivery person</h2></div>{onEdit && <button className="rounded-xl border border-blue-300 bg-white px-4 py-2 text-sm font-bold text-blue-800" type="button" onClick={onEdit}>Edit delivery person</button>}</div><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Info label="Name" value={assignment.deliveryPersonName} /><Info label="Delivery person ID" value={assignment.deliveryPersonId} /><Info label="Phone" value={assignment.deliveryPersonPhone} /><Info label="Assigned" value={formatDate(assignment.assignedAt)} /><Info label="Assigned by" value={assignment.assignedBy} />{assignment.note && <Info label="Internal note" value={assignment.note} />}</dl></section>;
}

export function AdminOrderDetailPage({ completedView = false }) {
  const { id } = useParams();
  const navigate = useNavigate();
  const [state, setState] = useState({ status: "loading", order: null, error: "" });
  const [action, setAction] = useState({ busy: false, error: "", message: "" });
  const [assignment, setAssignment] = useState({ deliveryPersonId: "", deliveryPersonName: "", deliveryPersonPhone: "", note: "" });
  const [editingAssignment, setEditingAssignment] = useState(false);
  const [dispatchNote, setDispatchNote] = useState("");
  const [deliveryNote, setDeliveryNote] = useState("");
  const [failure, setFailure] = useState({ reason: "beneficiary_unreachable", note: "" });
  const [proof, setProof] = useState({ file: null, progress: 0, error: "" });

  useEffect(() => { let active = true; adminOrdersApi.get(id).then((result) => { if (active) { const order = result.order || result; setState({ status: "ready", order, error: "" }); if (order.deliveryAssignment) setAssignment({ deliveryPersonId: order.deliveryAssignment.deliveryPersonId || "", deliveryPersonName: order.deliveryAssignment.deliveryPersonName || "", deliveryPersonPhone: order.deliveryAssignment.deliveryPersonPhone || "", note: order.deliveryAssignment.note || "" }); } }).catch((error) => { if (active) setState({ status: "error", order: null, error: error.message }); }); return () => { active = false; }; }, [id]);
  async function perform(task, message) { setAction({ busy: true, error: "", message: "" }); try { await task(); const result = await adminOrdersApi.get(id); setState({ status: "ready", order: result.order || result, error: "" }); setAction({ busy: false, error: "", message }); return true; } catch (error) { setAction({ busy: false, error: error.message, message: "" }); return false; } }
  function chooseProof(event) { const file = event.target.files?.[0] || null; if (!file) return; const error = validateRequestFile(file); setProof({ file: error ? null : file, progress: 0, error }); event.target.value = ""; }

  async function confirmDelivery() {
    if (!proof.file) return setProof((current) => ({ ...current, error: "Add proof of delivery before confirming delivery." }));
    if (!window.confirm("Confirm delivery, mark this order completed, and email the customer?")) return;
    setAction({ busy: true, error: "", message: "" });
    try { const uploaded = await uploadProtectedDeliveryProof(id, proof.file, (progress) => setProof((current) => ({ ...current, progress }))); await adminOrdersApi.confirmDelivery(id, { proofReference: uploaded.fileReference || uploaded.id, deliveryNote }); navigate(`/admin/completed-orders/${encodeURIComponent(id)}`, { replace: true }); }
    catch (error) { setAction({ busy: false, error: error.message, message: "" }); }
  }

  if (state.status === "loading") return <main className={pagePadding}><Loading /></main>;
  if (state.status === "error" && !state.order) return <main className={pagePadding}><ErrorMessage message={state.error} /></main>;
  const order = state.order;
  const isCompleted = ["completed", "delivered"].includes(order.status);
  const isOutForDelivery = order.status === "out_for_delivery";
  const canPrepareDelivery = ["payment_confirmed", "delivery_failed"].includes(order.status);
  const archiveView = completedView || isCompleted;
  return <main className={pagePadding}><Link className="text-sm font-bold text-slate-500 hover:text-emerald-700" to={archiveView ? "/admin/completed-orders" : "/admin/orders"}>← {archiveView ? "Completed orders" : "Order queue"}</Link><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-emerald-700">{archiveView ? "Completed order" : "Fulfillment order"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{order.orderNumber || id}</h1><p className="mt-2 text-sm text-slate-600">Verified payment: {order.payment?.paymentNumber}</p></div><span className="self-start rounded-full bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-800">{order.statusLabel || String(order.status).replaceAll("_", " ")}</span></div>{archiveView ? <div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><strong>Delivery completed.</strong> This order is archived as read-only, so delivery cannot be submitted again.</div> : <div className="mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><strong>Operational and medication information.</strong> Access and status changes must be logged by the server.</div>}{action.error && <ErrorMessage message={action.error} />}{action.message && <div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900" role="status">{action.message}</div>}
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><div className="space-y-6"><section className="rounded-[2rem] border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">Items to fulfill</h2><div className="mt-5 divide-y divide-slate-100">{order.items?.map((item,index) => <div key={item.id || index} className="py-4"><div className="flex justify-between gap-4 text-sm"><div><p className="font-bold">{item.medicationName}</p><p className="mt-1 text-slate-500">{item.strength} · {item.dosageForm} · {item.quantity} {item.unitLabel}</p></div><p className="font-bold">{item.fulfillmentStatusLabel || "Pending"}</p></div>{item.pharmacyNote && <p className="mt-2 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{item.pharmacyNote}</p>}</div>)}</div></section><section className="rounded-[2rem] border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">Beneficiary and delivery</h2><dl className="mt-6 grid gap-6 sm:grid-cols-2"><Info label="Beneficiary" value={order.beneficiary?.fullName} /><Info label="Phone" value={order.beneficiary?.phone} /><Info label="Address" value={order.delivery?.address || order.deliveryAddress} /><Info label="Instructions" value={order.delivery?.instructions} /></dl></section><section className="rounded-[2rem] border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">Internal order timeline</h2>{order.internalTimeline?.length ? <ol className="mt-5 space-y-4">{order.internalTimeline.map((event,index) => <li key={event.id || index} className="border-l-2 border-emerald-200 pl-4"><p className="text-xs text-slate-500">{formatDate(event.createdAt)}</p><p className="mt-1 text-sm font-bold">{event.internalLabel || event.label}</p><p className="mt-1 text-xs text-slate-500">By {event.actor?.name || "System"}</p></li>)}</ol> : <p className="mt-3 text-sm text-slate-600">Order creation after verified payment is the first internal event.</p>}</section></div>
      <aside className="space-y-6">{archiveView ? <><section className="rounded-[2rem] border border-emerald-200 bg-emerald-50 p-6"><h2 className="text-lg font-bold text-emerald-950">Completed order record</h2><p className="mt-3 text-sm leading-6 text-emerald-900">Delivery actions are disabled. Review the order and internal timeline here without changing its completed status.</p></section>{order.deliveryAssignment && <DeliveryPersonSummary assignment={order.deliveryAssignment} />}</> : <><section className="rounded-[2rem] border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">Simple fulfillment flow</h2><p className="mt-3 text-sm leading-6 text-slate-600">After payment, assign delivery and mark the order <strong>Out for Delivery</strong>. Finish with <strong>Completed</strong> or <strong>Delivery Failed</strong>.</p></section>
        {(canPrepareDelivery || isOutForDelivery) && order.deliveryAssignment && !editingAssignment && <DeliveryPersonSummary assignment={order.deliveryAssignment} onEdit={() => { setAssignment({ deliveryPersonId: order.deliveryAssignment.deliveryPersonId || "", deliveryPersonName: order.deliveryAssignment.deliveryPersonName || "", deliveryPersonPhone: order.deliveryAssignment.deliveryPersonPhone || "", note: order.deliveryAssignment.note || "" }); setEditingAssignment(true); }} />}
        {(canPrepareDelivery || isOutForDelivery) && (!order.deliveryAssignment || editingAssignment) && <section className="rounded-[2rem] border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">{order.deliveryAssignment ? "Edit delivery person" : "Delivery assignment"}</h2><p className="mt-2 text-xs leading-5 text-slate-500">Assignment details are internal and are not returned to the customer unless explicitly approved.</p><form className="mt-5 space-y-4" onSubmit={async (event) => { event.preventDefault(); if (await perform(() => adminOrdersApi.assignDelivery(id, assignment), order.deliveryAssignment ? "Delivery person updated." : "Delivery assignment saved.")) setEditingAssignment(false); }}><label className="block text-sm font-bold">Delivery person ID<input className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal" value={assignment.deliveryPersonId} onChange={(event) => setAssignment({ ...assignment, deliveryPersonId: event.target.value })} /></label><label className="block text-sm font-bold">Name<input className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal" value={assignment.deliveryPersonName} onChange={(event) => setAssignment({ ...assignment, deliveryPersonName: event.target.value })} /></label><label className="block text-sm font-bold">Phone<input className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal" type="tel" value={assignment.deliveryPersonPhone} onChange={(event) => setAssignment({ ...assignment, deliveryPersonPhone: event.target.value })} /></label><label className="block text-sm font-bold">Internal note<textarea className="mt-2 min-h-20 w-full rounded-xl border border-slate-300 p-3 font-normal" value={assignment.note} onChange={(event) => setAssignment({ ...assignment, note: event.target.value })} /></label><div className="flex gap-3">{order.deliveryAssignment && <button className="flex-1 rounded-xl border border-slate-300 px-4 py-3 text-sm font-bold text-slate-700" type="button" onClick={() => setEditingAssignment(false)} disabled={action.busy}>Cancel</button>}<button className="flex-1 rounded-xl bg-blue-800 px-4 py-3 text-sm font-bold text-white" type="submit" disabled={action.busy}>{order.deliveryAssignment ? "Save changes" : "Assign delivery"}</button></div></form></section>}
        {canPrepareDelivery && <section className="rounded-[2rem] border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">Dispatch order</h2><label className="mt-4 block text-sm font-bold">Customer-visible dispatch note<textarea className="mt-2 min-h-20 w-full rounded-xl border border-slate-300 p-3 font-normal" value={dispatchNote} onChange={(event) => setDispatchNote(event.target.value)} /></label><button className="mt-4 w-full rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white" type="button" disabled={action.busy} onClick={() => { if (window.confirm("Mark this order out for delivery and send the combined payment-confirmed/order-dispatched email?")) perform(() => adminOrdersApi.dispatch(id, { note: dispatchNote }), "Order dispatched."); }}>Mark out for delivery</button></section>}
        {isOutForDelivery && <section className="rounded-[2rem] border border-emerald-200 bg-emerald-50 p-6"><h2 className="text-lg font-bold text-emerald-950">Confirm delivery</h2><p className="mt-2 text-sm text-emerald-900">Upload appropriate proof and add a customer-safe delivery note.</p><label className="mt-4 block rounded-xl border-2 border-dashed border-emerald-300 bg-white p-4 text-center text-sm font-bold text-emerald-800">Choose proof of delivery<input className="sr-only" type="file" accept="image/jpeg,image/png,application/pdf" onChange={chooseProof} /></label>{proof.file && <div className="mt-3 rounded-xl bg-white p-3 text-sm"><p className="truncate font-bold">{proof.file.name}</p>{proof.progress > 0 && <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-emerald-600" style={{ width: `${proof.progress}%` }} /></div>}</div>}{proof.error && <p className="mt-2 text-sm font-semibold text-red-700">{proof.error}</p>}<label className="mt-4 block text-sm font-bold text-emerald-950">Delivery note<textarea className="mt-2 min-h-20 w-full rounded-xl border border-emerald-300 bg-white p-3 font-normal" value={deliveryNote} onChange={(event) => setDeliveryNote(event.target.value)} /></label><button className="mt-4 w-full rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white" type="button" disabled={action.busy} onClick={confirmDelivery}>Confirm delivered</button></section>}
        {isOutForDelivery && <section className="rounded-[2rem] border border-red-200 bg-red-50 p-6"><h2 className="text-lg font-bold text-red-950">Delivery failure</h2><form className="mt-4 space-y-4" onSubmit={(event) => { event.preventDefault(); if (!failure.note.trim()) return; if (window.confirm("Record this delivery failure and email the customer?")) perform(() => adminOrdersApi.recordDeliveryFailure(id, failure), "Delivery failure recorded."); }}><label className="block text-sm font-bold text-red-950">Reason<select className="mt-2 w-full rounded-xl border border-red-300 bg-white px-4 py-3 font-normal" value={failure.reason} onChange={(event) => setFailure({ ...failure, reason: event.target.value })}><option value="beneficiary_unreachable">Beneficiary unreachable</option><option value="address_issue">Address issue</option><option value="delivery_refused">Delivery refused</option><option value="vehicle_or_route_issue">Vehicle or route issue</option><option value="other">Other</option></select></label><label className="block text-sm font-bold text-red-950">Required note<textarea className="mt-2 min-h-24 w-full rounded-xl border border-red-300 bg-white p-3 font-normal" value={failure.note} onChange={(event) => setFailure({ ...failure, note: event.target.value })} /></label><button className="w-full rounded-xl bg-red-800 px-4 py-3 text-sm font-bold text-white" type="submit" disabled={action.busy || !failure.note.trim()}>Record delivery failure</button></form></section>}</>}</aside></div>
  </main>;
}
